# Generated by Django 6.0.1 on 2026-02-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_order_payment_status_order_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="razorpay_signature",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("SOLAR_PANEL", "Solar Panels"),
                    ("INVERTER", "Inverters"),
                    ("BATTERY", "Batteries"),
                    ("MOUNTING", "Mounting Structures"),
                    ("WATER_HEATER", "Water Heaters"),
                    ("ACCESSORIES", "Accessories"),
                    ("CLEANING", "Cleaning Equipment"),
                ],
                default="ACCESSORIES",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("ONLINE", "Online Payment")],
                default="COD",
                max_length=20,
            ),
        ),
    ]
