# Generated by Django 6.0.1 on 2026-02-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("SOLAR_PANELS", "Solar Panels"),
                    ("INVERTERS", "Inverters"),
                    ("BATTERIES", "Batteries"),
                    ("WATER_HEATERS", "Water Heaters"),
                    ("ACCESSORIES", "Accessories"),
                    ("MOUNTING", "Mounting Structures"),
                    ("CLEANING", "Cleaning Systems"),
                ],
                default="ACCESSORIES",
                max_length=50,
            ),
        ),
    ]
